use_frameworks!

platform :ios, '10.0'

target 'DogLib_Example' do
  pod 'DogLib', :path => '../', :testspecs => ['UnitTests']
  pod 'ProgressHUD'

  target 'DogLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.1'
    pod 'Nimble', '~> 10.0.0'
  end
end
